Repository f-lab-edu/number-baseball-game, pull requests merged in 2022-07, with the labels that each got.

#3 feature: 숫자 야구 게임 뼈대 작성
  app/src/main/java/edu/number/baseball/App.java
  app/src/main/java/edu/number/baseball/game/NumberBaseBallGame.java
Labels: enhancement, good first issue

#8 feat: basic random number generation rule #4
  app/src/main/java/edu/number/baseball/TargetNumbers.java
  app/src/main/java/edu/number/baseball/game/NumberBaseBallGame.java
  app/src/main/java/edu/number/baseball/randomnumber/MathRandomRule.java
  app/src/main/java/edu/number/baseball/randomnumber/RandomNumberGenerationRule.java
  app/src/test/java/edu/number/baseball/NumberBaseballPitchingTest.java
Labels: enhancement

#7 생성된 숫자와 유저 입력 숫자 비교 결과 생성
  .gitignore
  app/build.gradle
  app/src/main/java/edu/number/baseball/InputNumbers.java
  app/src/main/java/edu/number/baseball/NumberBaseballPitching.java
  app/src/main/java/edu/number/baseball/Numbers.java
  app/src/main/java/edu/number/baseball/PitchingResult.java
  app/src/main/java/edu/number/baseball/TargetNumbers.java
  app/src/main/java/edu/number/baseball/game/NumberBaseBallGame.java
  app/src/main/java/edu/number/baseball/randomnumber/MathRandomRule.java
  app/src/main/java/edu/number/baseball/randomnumber/RandomNumberGenerationRule.java
  app/src/test/java/edu/number/baseball/AppTest.java
  app/src/test/java/edu/number/baseball/NumberBaseballPitchingTest.java
Labels: enhancement

#9 #6 사용자로 부터 입력받고 검증하는 작업
  app/build.gradle
  app/src/main/java/edu/number/baseball/NumberBaseballPitching.java
  app/src/main/java/edu/number/baseball/domain/InputNumbers.java
  app/src/main/java/edu/number/baseball/domain/Numbers.java
  app/src/main/java/edu/number/baseball/domain/PitchingResult.java
  app/src/main/java/edu/number/baseball/domain/TargetNumbers.java
  app/src/main/java/edu/number/baseball/exception/WrongInputRepeatException.java
  app/src/main/java/edu/number/baseball/game/NumberBaseBallGame.java
  app/src/main/java/edu/number/baseball/util/io/IntegerArrayReader.java
  app/src/main/java/edu/number/baseball/util/io/NumbersReader.java
  app/src/main/java/edu/number/baseball/util/io/StringNumbersReader.java
  app/src/main/java/edu/number/baseball/util/valid/InputValidator.java
  app/src/test/java/edu/number/baseball/NumberBaseballPitchingTest.java
  app/src/test/java/edu/number/baseball/util/io/NumbersReaderTest.java
  app/src/test/java/edu/number/baseball/util/valid/InputValidatorTest.java
  app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: enhancement

#11 feat: implement restart logic and prettier pitching result #10
  app/src/main/java/edu/number/baseball/App.java
  app/src/main/java/edu/number/baseball/NumberBaseballPitching.java
  app/src/main/java/edu/number/baseball/domain/PitchingResult.java
Labels: enhancement

#12 첫 Main 브랜치 릴리즈
  .gitignore
  app/build.gradle
  app/src/main/java/edu/number/baseball/App.java
  app/src/main/java/edu/number/baseball/NumberBaseballPitching.java
  app/src/main/java/edu/number/baseball/domain/InputNumbers.java
  app/src/main/java/edu/number/baseball/domain/Numbers.java
  app/src/main/java/edu/number/baseball/domain/PitchingResult.java
  app/src/main/java/edu/number/baseball/domain/TargetNumbers.java
  app/src/main/java/edu/number/baseball/exception/WrongInputRepeatException.java
  app/src/main/java/edu/number/baseball/game/NumberBaseBallGame.java
  app/src/main/java/edu/number/baseball/randomnumber/MathRandomRule.java
  app/src/main/java/edu/number/baseball/randomnumber/RandomNumberGenerationRule.java
  app/src/main/java/edu/number/baseball/util/io/IntegerArrayReader.java
  app/src/main/java/edu/number/baseball/util/io/NumbersReader.java
  app/src/main/java/edu/number/baseball/util/io/StringNumbersReader.java
  app/src/main/java/edu/number/baseball/util/valid/InputValidator.java
  app/src/test/java/edu/number/baseball/AppTest.java
  app/src/test/java/edu/number/baseball/NumberBaseballPitchingTest.java
  app/src/test/java/edu/number/baseball/util/io/NumbersReaderTest.java
  app/src/test/java/edu/number/baseball/util/valid/InputValidatorTest.java
  app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: enhancement

#13 Develop 브랜치 업데이트
  README.md
Labels: documentation, duplicate

#17 .gitignore bin directory
  .gitignore
Labels: enhancement

#15 #14 게임 결과 기록및 승리 시 종료
  README.md
  app/src/main/java/edu/number/baseball/domain/PitchingResult.java
  app/src/main/java/edu/number/baseball/game/NumberBaseBallGame.java
  app/src/main/java/edu/number/baseball/util/io/write/ResultFileWrite.java
Labels: enhancement
